# fly.toml app configuration file generated for bot-trading-btcusdt on 2025-06-05T00:32:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-trading-btcusdt'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.checks]]
    type = "http"
    interval = "10s"
    timeout = "5s"
    method = "get"
    path = "/health"
    protocol = "http"